# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: epp 1.5.1 ruby lib

Gem::Specification.new do |s|
  s.name = "epp"
  s.version = "1.5.1"

  s.required_ruby_version = ">= 3.0.0"
  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Josh Delsman", "Sergei Tsõganov"]
  s.date = "2014-12-08"
  s.description = "Ruby client for EPP (Extensible Provisioning Protocol, RFC 5730): framed XML over TLS, with libxml-ruby for requests and Nokogiri for responses."
  s.email = ["jdelsman@ultraspeed.com", "sergei.tsoganov@internet.ee"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "CHANGELOG.md",
    "Dockerfile",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "epp.gemspec",
    "lib/epp.rb",
    "lib/epp/exceptions.rb",
    "lib/epp/server.rb",
    "lib/require_parameters.rb",
    "test/test_epp.rb",
    "test/test_helper.rb",
    "test/xml/error.xml",
    "test/xml/login_request.xml",
    "test/xml/login_response.xml",
    "test/xml/login_with_extensions_request.xml",
    "test/xml/logout_request.xml",
    "test/xml/logout_response.xml",
    "test/xml/new_request.xml",
    "test/xml/socket_preparation.xml",
    "test/xml/test_request.xml",
    "test/xml/test_response.xml"
  ]
  s.homepage = "https://github.com/internetee/epp"
  s.metadata = {
    "bug_tracker_uri" => "https://github.com/internetee/epp/issues",
    "changelog_uri" => "https://github.com/internetee/epp/blob/master/CHANGELOG.md",
    "documentation_uri" => "https://github.com/internetee/epp/blob/master/README.rdoc",
    "homepage_uri" => "https://github.com/internetee/epp",
    "source_code_uri" => "https://github.com/internetee/epp"
  }
  s.rubygems_version = "2.2.2"
  s.summary = "Ruby client for EPP (Extensible Provisioning Protocol) over TLS"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.8"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.8"])
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.8"])
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
  end
end

